- CHANGELOG.md
- package.json
If you don't have a changelog things crash, and if your version in your package.json is higher than your last tag nothing happens
> reset version so release-plan will work on itself

- src/cli.ts
- src/plan.ts
- src/prepare.ts
release-plan was originally designed to only work in monorepos, which makes a lot of sense because that's where it really shines!
There is however some value in running it in repos that only have one package in it because of the way that the deployment workflow happens so this PR adds a mode where you pass `--single-package=something` to bypass the code that figures out all the packages
This could probably be removed in future, I was just looking for the fastest way to implement this feature so it unblocked me 👍
> add --single-package option

- .github/workflows/publish.yml
- .github/workflows/release-plan-preview.yml
I don't know why it's not actually registering the binary 🤔
> use dist/cli.js directly in workflows

- src/plan.ts
If lerna-changelog reports a package that has changed that is set to `private: true` release-plan would throw because it didn't find that package in its plan.
This PR fixes that 👍
> don't throw when we encounter an unknown package

- src/cli.ts
- src/gather-changes.ts
This fixes a problem when you are trying to run release-plan in a consuming repo, it wouldn't be able to find the version of lerna-changelog that we need. This PR fixes that 🎉
> use require.resolve to find lerna-changelog

- .eslintrc.cjs
- src/cli.ts
This was accidentially removed in #29 because of an overly-aggressive `lint --fix` 🙈
> add shebang back and fix linting config

- .eslintrc.cjs
- .github/workflows/ci.yml
- fixtures/pnpm/star-package/files/package.json
- fixtures/pnpm/star-package/package.json
- fixtures/pnpm/star-package/pnpm-workspace.yaml
- fixtures/pnpm/star-package/tests/package.json
- package.json
- pnpm-lock.yaml
- src/interdep.test.ts
- src/interdep.ts
- tsconfig.json
for the [addon-blueprint](https://github.com/embroider-build/addon-blueprint) one of the packages that we want to deploy is the root package, and it was using a glob for the package list
This PR adds a sample fixture that matches the addon-blueprint and adds a new test suite that checks that package discovery is as expected 👍
> Fix pnpm package discovery

- src/cli.ts
- src/publish.test.ts
- src/publish.ts
This allows us to pass on the required [--publish-branch config](https://pnpm.io/cli/publish#--publish-branch-branch) whenever we're trying to release on a branch other than main or master 👍 
I added a test for the main function that changed too 🎉
> add --publish-branch if passed to release-plan publish

- src/cli.ts
- src/publish.test.ts
- src/publish.ts
This is helpful if you're using release plan for a legacy branch and don't want it to be released as `latest`
> add ability to pass tag to publish command

- src/plan.ts
I'm not exactly sure why this was working 🤔 semver hasn't been swapped over to a ESM module so it's not an upstream issue but I got an error complaining about this: 
https://github.com/emberjs/ember-optional-features/actions/runs/7904746758/job/21575788951#step:5:15
Edit: I've tested this locally and I'm happy enough with it to merge without waiting for a review 👍
> fix import of semver

- package.json
- pnpm-lock.yaml
- src/change-parser.ts
This will make sure that if you don't have any config release-plan notices to tag the "Aditional Changes" as "unlabelled"
> add the default github-changelog unlabelled section name to parser

- .gitignore
- package.json
- pnpm-lock.yaml
- src/publish.test.ts
- src/publish.ts
I wanted to update latest-version but it crossed a few major boundaries so I thought I should exercise it first 👍 
I've marked this as a bugfix because it clears out a security warning in downstream repos: https://github.com/ember-cli/babel-plugin-debug-macros/security/dependabot/108
> add a test to exercise latest-version dependency and update it

- src/cli.ts
- src/publish.test.ts
- src/publish.ts
Closes #80 
Changes:
- Update the `--dry-run` flag so it is passed to `pnpm publish` to get more useful feedback.
- Remove the hardcoded `--access=public` argument and instead allow users to pass the `--access` flag with `public` or `restricted` set.  
Previously, running `pnpm release-plan publish` would force any package to publish as public, even if the access was set to restricted in the package.json.  
This change better matches the default behavior of `pnpm publish` and allows scoped packages to avoid being switched to public accidentally. 
With this change, the expected behaviors are:
1. Running publish without an `--access` flag will respect the [publishConfig](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#publishconfig) access set in `package.json`
2. Running …
> Add support for specifying --access, aligning better with default publish behavior

- README.md
- package.json
- pnpm-lock.yaml
- src/plan.test.ts
- src/plan.ts
implement optional configuration of increment level passed to semver library
for pre 1.0 packages this is needed to override breaking changes pushing the package major version number
> add semverIncrementAs option for granular package version control

- src/plan.test.ts
- src/plan.ts
This just allows you to have prereleases with versions like `2.0.0-alpha.0` rather than just `2.0.0-0`
> allow you to define a semver tag when using prerelease

- src/publish.test.ts
- src/publish.ts
currently the release name defaults to  something like `v3.8.1-@embroider/compat: Merge pull request #2248 from embroider-build/release-preview-stable`.
this will make it just `v3.8.1-@embroider/compat`
> make name of release the same as the tag

- README.md
- src/publish.test.ts
- src/publish.ts
pass GITHUB_API_URL to Octokit baseUrl, if its undefined Octokit falls back to default value
same support in https://github.com/embroider-build/github-changelog/pull/33
> support github enterprise api url via env var

- src/prepare.test.ts
- src/prepare.ts
Since Markdown doesn't display single line breaks, either two line breaks can be used (althought this adds more padding above and below each line) or they can be treated as items of a list.
> feat: Display new package versions as list

- src/publish.test.ts
- src/publish.ts
Creating/pushing tags is the only place the `git` CLI is used (except for checking if the repository is "clean" in `hasCleanRepo`). Since the `git` command uses the provided `GITHUB_TOKEN` from GitHub Actions but a different token can be provided via `GITHUB_AUTH`, different users would be in charge of creating tags and creating releases.
The GitHub REST API can also [create a tag](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release) when creating a release via the `target_commitish` property:
> Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
By creating the tags via Octokit with the REST API, we can …
> refactor: Create tags via GitHub REST API

- README.md
I was adding a new command line argument and when I went to document it I was shocked to find we didn't actually document our command-line arguments anywhere 🫠 
This PR adds a section for command-line argument docs 👍
> add documentation for command-line arguments
